[package]
name = "async-mongodb-session"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/async-mongodb-session"
documentation = "https://docs.rs/async-mongodb-session"
description = "An async-session implementation for MongoDB"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
    "Irina Shestak <shestak.irina@gmail.com>",
]

[features]

[dependencies]
# mongodb = { version = "1.0.0", default-features = false, features = ["async-std-runtime"] }
mongodb = { git = "https://github.com/saghm/mongo-rust-driver", default-features = false, branch = "RUST-452", features = ["async-std-runtime"] }
async-session = "2.0.0"
async-trait = "0.1.36"
serde_json = "1.0.56"

[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
